### PR TITLE
Add option for disabling NVC `--jit`

### PR DESCRIPTION
**Pull request by albydnc**
Fix for issue https://github.com/VUnit/vunit/issues/1014

### CODE REVIEW

**Comment by LarsAsplund** [comment]
When it comes to simulator options that are not among the more common ones, we provide `nvc.sim_flags` rather than a more dedicated one. That would work in this case, right?

**Comment by albydnc** [comment]
Yes, but with `nvc.sim_flags` you can only add options, while you can't disable the default ones.
This option needed to be disabled due to a bug in order for nvc to work. See https://github.com/VUnit/vunit/issues/1014#issuecomment-2113479491
Since it is fixed, I will close the PR, but I think there should be a way to remove all default flags.

**Comment by LarsAsplund** [comment]
@albydnc Ah, now I see your point. You're right, there should be such a feature but let's await the next use case. Whatever the solution is, it should probably be common to all simulators.

**Comment by albydnc** [comment]
I agree with you, it should be a generic thing.

**Pull request closed without merging**
