### PR TITLE
fix parsing adjacent hyphens in a literal

### PR DESCRIPTION
**Pull request by ktbarrett**
Addresses #529 by improving the comment removal regular expression. But this time it actually works!

Will rebase into a single commit tonight.

### CODE REVIEW

**Comment by kraigher** [comment]
I am ready to merge this if the checks pass. Do you need any help on how to run the checks locally?

**Comment by kraigher** [comment]
I saw that you pushed a fix the same second I wrote the comment, good :-)

**Comment by ktbarrett** [comment]
@kraigher I do not have the current master or black locally to check. I looked at the checks to see where it failed. If it is more work than that, I will have to wait until tonight.

**Comment by kraigher** [comment]
You should be able to run black using just:

```console
> python -m pip install tox
> python -m tox -e py37-fmt
```
Where you can replace py37 which whatever version you have.

**Comment by ktbarrett** [comment]
> `> python -m pip install tox`

I can't download anything where I am. If you want this in today, feel free to make any changes.

**Comment by eine** [comment]
@ktbarrett, if this is just an issue with running black once, I'll pick it later. Otherwise, I'll push the format fix and leave it open.

**Comment by eine** [comment]
I pushed linter fixes, but CI jobs seems to be stalled regardless. These are the last three attempts:

- https://github.com/VUnit/vunit/runs/405634137
- https://github.com/VUnit/vunit/runs/405693815
- https://github.com/VUnit/vunit/runs/405868716

**Comment by ktbarrett** [comment]
@eine Thanks.

I'm home now. How do I recreate the environment the regressions run in? I'm assuming there is some assumed set of tools the regression work with. Just running tox locally leads to all the acceptance tests failing. And is there anyway to increase the verbosity of the tests while they are running? What I have now is not enough to go forward.

**Comment by eine** [comment]
> I'm home now. How do I recreate the environment the regressions run in? I'm assuming there is some assumed set of tools the regression work with. Just running tox locally leads to all the acceptance tests failing.

The environment just requires a simulator (GHDL is used in the CI workflow) and `tox`. Then, execute `tox -e py38-acceptance-ghdl` in the root of the repo. If you have docker/podman, you can use the following command to run a container  (instead of installing GHDL on your host):

```sh
docker run --rm -tv $(pwd):/src -w /src ghdl/vunit:llvm bash -c "pip3 install to; tox -e py38-acceptance-ghdl"
```

>  And is there anyway to increase the verbosity of the tests while they are running? What I have now is not enough to go forward.

Tests are in subdir `tests`. However, I suggest to run all of them, and then copy the full name of the ones you want to further test. In `tox.ini` you will find the `pytest` command. For example:

```sh
pytest -v tests/acceptance/test_artificial.py::TestVunitArtificial::test_artificial_verilog
```

However, it seems to be failing when testing external run scripts. These are, indeed, the examples. Hence, you can first try to execute each example individually.

**Comment by ktbarrett** [comment]
The old pattern was correct, but *really* slow, so I optimized. I'm running raw times master vs this PR to see the effect on performance.

**Comment by eine** [comment]
All tests pass and there seems to be no time penalty any more. However, no specific test is added. That'd be interesting  to prevent future regressions. Anyway, @ktbarrett, I'm ok with merging if you confirm that the examples you were trying in #529 do work now.

**Comment by ktbarrett** [comment]
@eine I have confirmed that these fix my issues locally. I can add a unit test to the regression as well.

**Comment by eine** [comment]
Thanks. Please, go ahead on this same PR.

**Pull request merged**
