### PR TITLE
Allow recovery on preprocessing failure

### PR DESCRIPTION
**Pull request by bradleyharden**
When attempting to add a file with syntax errors, VUnit will
report that an error has occurred and skip preprocessing for
the file. A unit test for this case has also been added.

### CODE REVIEW

**Comment by bradleyharden** [comment]
What's going on with this? It doesn't look like any of these errors have to do with me. Is there an issue with the Travis environment?

**Comment by kraigher** [comment]
@bradleyharden a recent update to GHDL has started to make VUnit regression tests fail: https://travis-ci.org/VUnit/vunit/jobs/433187950. There is no problem with your commit. We have to get GHDL fixed or work-arround the bug then this PR has to be rebased.

**Comment by bradleyharden** [comment]
@kraigher Any idea when that will be?

**Comment by kraigher** [comment]
The ghdl project is usually quite fast so any day now. On the other hand I could just use an older ghdl for Travis temporarily.

**Pull request merged**
